apiVersion: v1
kind: Namespace
metadata:
  name: summit2
  namespace: summit2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ld-summit-frontend
  namespace: summit2
  labels:
    app: ld-summit-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ld-summit-frontend
  template:
    metadata:
      annotations:
        "prometheus.io/scrape": "true"
        "prometheus.io/port": "5670"
      labels:
        app: ld-summit-frontend
    spec:
      containers:
        - name: ld-summit-frontend
          image: codydearkland/ld-summit-frontend:2
          imagePullPolicy: Always
          ports:
            - name: web
              containerPort: 3000
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: ld-summit-frontend
  namespace: summit2
spec:
  ports:
    - name: http
      port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    app: ld-summit-frontend
---
apiVersion: v1
kind: Service
metadata:
  namespace: summit2
  name: ld-lb
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: ld-summit-frontend
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: summit2
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      annotations:
        "prometheus.io/scrape": "true"
        "prometheus.io/port": "5670"
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: codydearkland/ld-summit-api:2
          imagePullPolicy: Always
          ports:
            - containerPort: 5010
---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: summit2
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 5010
      targetPort: 5010
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: summit2
  labels:
    app: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      annotations:
        "prometheus.io/scrape": "true"
        "prometheus.io/port": "5670"
      labels:
        app: db
    spec:
      containers:
        - name: db
          image: codydearkland/db:summit
          imagePullPolicy: Always
          ports:
            - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: summit2
spec:
  selector:
    app: db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
